### ISSUE TITLE
make ssh_keypair name as a variable in REL_1_0_1

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/postgres-deployment#14]
Currently, ssh_keypair is using the keypath. Please make it to use the PROJECT_NAME_key-pair name for the key pair. 
If we use the key pair name same as keypath, then we are getting errors for multiple projects due to the duplicate key name in AWS.

**Comment by dougortiz** [comment]
Functionality has been added to AWS 'postgres-deployments' repository.

In progress:
- Azure
- Google Cloud
- edb-ansible repository

**Comment by dougortiz** [comment]
Updated ssh_keypair functionality as requested for:
- AWS Terraform
- Azure Terraform
- Google Cloud Terraform
- AWS Postgres Install
- Azure Postgres Install
- Google Cloud Postgres Install

Functionality has been tested on all tasks listed above.

**Comment by vibhorkumar123** [comment]
Can you please re-confirm if this fix in the REL-1_0_1 branch?

**Comment by dougortiz** [comment]
This fix is in the REL-1_0_1 branch.

**Comment by dougortiz** [comment]
@vibhorkumar123 - Ready for testing

**Comment by dougortiz** [comment]
Tested on AWS:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS8, CentOS7, RHEL8
RHEL7 no longer available

**Comment by dougortiz** [comment]
Tested on Azure:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS7, CentOS8, RHEL7, RHEL8
Single Installation
EPAS 13

**Comment by dougortiz** [comment]
Tested on Google Cloud:
Tested on Azure:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS7, CentOS8, RHEL7, RHEL8
Single Installation
EPAS 12
