### ISSUE TITLE
edb-deployment destroy doesn't clean up the project's artifacts and configuration

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/postgres-deployment#19]
edb-deployment destroy command should remove the artifacts and configuration from projects/<cloudname> directory

**Comment by dougortiz** [comment]
Tested on AWS:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS8, CentOS7, RHEL8
RHEL7 no longer available

**Comment by dougortiz** [comment]
Tested on Azure:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS7, CentOS8, RHEL7, RHEL8
Single Installation
EPAS 13

**Comment by dougortiz** [comment]
Tested on Google Cloud:
Tested on Azure:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS7, CentOS8, RHEL7, RHEL8
Single Installation
EPAS 12
