### ISSUE TITLE
Add AMI Functionality where applicable to AWS, Azure and Google Cloud

### ISSUE THREAD

**Issue by dougortiz** [EnterpriseDB/postgres-deployment#26]
* Do you want to use custom AMI (Yes/No)?
    - Enter AMI ID

**Comment by dougortiz** [comment]
Only applies to AWS
AWS - Testing

**Comment by dougortiz** [comment]
AWS - AMI ID has been added to configuration file and is working successfully

**Comment by vibhorkumar123** [comment]
It is specific to AWS. Already tested for AWS.
