### ISSUE TITLE
GCloud: Allow user to choose encrypted volume 

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/postgres-deployment#37]
Allow users to add encrypted volume on their provisioned VM.

**Comment by dougortiz** [comment]
Tested successfully:

- CentOS8 - Single Node
- RHEL8 - Multi-Node

**Comment by dougortiz** [comment]
Tested successfully:
CentOS7 and CentOS8 - Single and Multi-Node Clusters
RHEL7 and RHEL8 - Single and Multi-Node Clusters

Encrypted Attached Disks are not fully supported as of yet in Terraform:
[(https://github.com/hashicorp/terraform-provider-google/issues/4448)]
