### ISSUE TITLE
GCloud - Add capability in the Edb cli for adding user defined volumes

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/postgres-deployment#39]
Add capability in the Edb cli for adding user defined volumes in GCloud

**Comment by dougortiz** [comment]
Tested successfully with Single Node Cluster

**Comment by dougortiz** [comment]
Tested successfully:
- CentOS 8 - Single Node
- RHEL 8 - Single Node
- CentOS 8 - Multi-Node
- RHEL 8 - Multi-Node

**Comment by dougortiz** [comment]
Successfully tested:
CentOS7 and CentOS8 - Single and Multi-Node Clusters
RHEL7 and RHEL8 - Single and Multi-Node Cluster
