### ISSUE TITLE
Group the subcommands of CLI based on cloud

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/postgres-deployment#45]
Group the CLI command as given below:
```
aws             
          servers   [create|destroy]   PROJECT_NAME
          postgres  install            PROJECT_NAME
          projects  list
                    switch             PROJECT_NAME
          config    [show|update]      PROJECT_NAME
 azure             
          servers   [create|destroy]   PROJECT_NAME
          postgres  install            PROJECT_NAME
          projects  list
                    switch             PROJECT_NAME
          config    [show|update]      PROJECT_NAME
 gcloud             
          servers   [create|destroy]   PROJECT_NAME
          postgres  install            PROJECT_NAME
          projects  list
                    switch             PROJECT_NAME
          config    [show|update]      PROJECT_NAME
```

**Comment by jt-edb** [comment]
I'm a bit scared by having 3 levels (platform/commands/subcommands) of arguments to describe the action we want to execute like this and would tend to a more concise semantic:
```shell
$ ./edb-deploy aws create-servers
$ ./edb-deploy azure install-postgres
$ ./edb-deploy gcloud show-config
```

What do you think @vibhorkumar123 ?

**Comment by vibhorkumar123** [comment]
Are you thinking something like the given below?
```function usage()
{
    echo ""
    echo "${BASENAME} [<cloud>-server|<cloud>-postgres] [OPTION]..."
    echo ""
    echo "EDB deployment script for aws, azure and gcp"
    echo ""
    echo "Subcommands:"
    echo "  [aws|azure|gcloud]"
    echo "          create-servers      project_name"
    echo "          install-postgres    project_name"
    echo "          show-config         project_name"
    echo "          switch-project      project_name"
    echo "          list-projects"
    echo "Other Options:"
    echo "    -h, --help Display help and exit"
    echo ""
    exit 1
}```

**Comment by jt-edb** [comment]
> Are you thinking something like the given below?

Yes, I do.

**Comment by vibhorkumar123** [comment]
Example of command with arguments
```
edb-deploy aws --project-name abc123 \
                             --yum-username xxx \
                             --yum-password xxx \
                             --reference-architecture [single-node|multi-node-asynchronous|mult-node-synchronous] \
                             --postgres-type PostgreSQL \
                             --database-size 200
```

**Comment by dougortiz** [comment]
Project Name argument was added for the following edb-cli-go commands:
- run
- install
- destroy
- delete

**Comment by dougortiz** [comment]
![image](https://user-images.githubusercontent.com/63114888/103106091-9b09ff00-4600-11eb-8a67-d691a16a220c.png)

**Comment by dougortiz** [comment]
Only AWS is supported in EDB-CLI-GO

**Comment by dougortiz** [comment]
![image](https://user-images.githubusercontent.com/63114888/103942723-d5929200-50fe-11eb-8cde-1b03a0960c20.png)

**Comment by dougortiz** [comment]
Tested successfully - AWS:
- Single Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Multi-Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
 
Regression tested successfully:
- Single Node Cluster EPAS: CentOS8 and RHEL8
- Multi-Node Cluster EPAS: CentOS8 and RHEL8

Tested successfully - Azure:
- Single Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Multi-Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Fails because of bug: EPAS - RHEL8: Single and Multi-Node Cluster

Tested successfully - GCP:
- Single Node Cluster - EPAS: CentOS7, CentOS8, RHEL7 and RHEL8
- Multi-Node Cluster - EPAS: CentOS7, CentOS8, RHEL7 and RHEL8

**Comment by vibhorkumar123** [comment]
The new Interface has more capabilities.
