### ISSUE TITLE
PEM Agent Install Fails Due to Incorrect/Incomplete Entries in pg_hba.conf on PEM Server

### ISSUE THREAD

**Issue by mlewandowski-edb** [EnterpriseDB/postgres-deployment#53]
When I ran the ./edb-deployment aws-postgres install command, the database servers and efm tasks completed successfully; however, the script encountered a fatal error during the pem setup steps.  Here is the snippet from the ansible output corresponding to the pem setup steps (fatal error shown at the end):

TASK [edb_devops.edb_postgres.setup_pem : reference ariables] ***************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_pem : Prepare etc_hosts_lists] **********************************************************
ok: [localhost] => (item={u'key': u'epas1', u'value': {u'public_ip': u'3.88.173.122', u'pem_agent': True, u'node_type': u'primary', u'public_dns': u'ec2-3-88-173-122.compute-1.amazonaws.com', u'hostname': u'epas1', u'private_ip': u'10.0.0.89'}})
ok: [localhost] => (item={u'key': u'epas3', u'value': {u'public_ip': u'54.85.77.218', u'pem_agent': True, u'node_type': u'standby', u'public_dns': u'ec2-54-85-77-218.compute-1.amazonaws.com', u'replication_type': u'asynchronous', u'hostname': u'epas3', u'private_ip': u'10.0.3.172'}})
ok: [localhost] => (item={u'key': u'epas2', u'value': {u'public_ip': u'54.80.197.100', u'pem_agent': True, u'node_type': u'standby', u'public_dns': u'ec2-54-80-197-100.compute-1.amazonaws.com', u'replication_type': u'asynchronous', u'hostname': u'epas2', u'private_ip': u'10.0.2.76'}})

TASK [edb_devops.edb_postgres.setup_pem : Get the pem_server_private/public_ip] *********************************************
ok: [localhost] => (item={u'key': u'pemserver', u'value': {u'public_ip': u'75.101.228.236', u'node_type': u'pemserver', u'public_dns': u'ec2-75-101-228-236.compute-1.amazonaws.com', u'private_ip': u'10.0.1.89'}})

TASK [edb_devops.edb_postgres.setup_pem : Get the primary_private/public_ip] ************************************************
ok: [localhost] => (item={u'key': u'epas1', u'value': {u'public_ip': u'3.88.173.122', u'pem_agent': True, u'node_type': u'primary', u'public_dns': u'ec2-3-88-173-122.compute-1.amazonaws.com', u'hostname': u'epas1', u'private_ip': u'10.0.0.89'}})
included: /home/matt/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_pem/tasks/prepare_hba_value_list.yml for localhost
included: /home/matt/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_pem/tasks/prepare_hba_value_list.yml for localhost
included: /home/matt/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_pem/tasks/prepare_hba_value_list.yml for localhost

TASK [edb_devops.edb_postgres.setup_pem : Prepare the list] *****************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_pem : Prepare array of list] ************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_pem : Prepare the list] *****************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_pem : Prepare array of list] ************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_pem : Prepare the list] *****************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_pem : Prepare array of list] ************************************************************
ok: [localhost]
included: /home/matt/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_pem/tasks/setup_pem.yml for localhost
included: /home/matt/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_pem/tasks/setup_pem.yml for localhost
included: /home/matt/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_pem/tasks/setup_pem.yml for localhost
included: /home/matt/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_pem/tasks/setup_pem.yml for localhost

TASK [edb_devops.edb_postgres.setup_pem : debug] ****************************************************************************
ok: [localhost] => {
    "msg": "operating system = CentOS8: pg_type = EPAS, node type = primary, pg_data = /data/pgdata, public ip = 3.88.173.122"
}

TASK [edb_devops.edb_postgres.setup_pem : set pem_agent based on the user input] ********************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.manage_dbserver : Create hidden pass directory if not exists] *********************************
ok: [localhost]

TASK [edb_devops.edb_postgres.manage_dbserver : Create passfile location] ***************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.manage_dbserver : Generate password or copy the password from pass file] **********************
ok: [localhost]

TASK [edb_devops.edb_postgres.manage_dbserver : Make sure file is has permission for owner only] ****************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_pem : Set pg_pem_agent_password] ********************************************************
ok: [localhost -> 3.88.173.122]

TASK [edb_devops.edb_postgres.manage_dbserver : Manage optional users] ******************************************************
changed: [localhost -> 3.88.173.122] => (item=None)
changed: [localhost]

TASK [edb_devops.edb_postgres.setup_pem : Install require packages for PEM agent] *******************************************
ok: [localhost -> 3.88.173.122]

TASK [edb_devops.edb_postgres.setup_pem : check if agent was registered] ****************************************************
ok: [localhost -> 3.88.173.122]

TASK [edb_devops.edb_postgres.setup_pem : install pem agent] ****************************************************************
fatal: [localhost -> 3.88.173.122]: FAILED! => {"changed": false, "cmd": "set -o pipefail\nset -eu\nPEM_SERVER_PASSWORD= /usr/edb/pem/agent/bin/pemworker     --register-agent     --display-name epas1     --pem-user pemadmin     --pem-server 10.0.1.89     --pem-port 5444     --allow_server_restart true     --allow-batch-probes true     --batch-script-user root\n", "delta": "0:00:00.090548", "end": "2020-11-18 16:07:53.268478", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2020-11-18 16:07:53.177930", "stderr": "Wed Nov 18 16:07:53 2020 WARNING: ConnectToPEM: unable to connect to PEM database: FATAL:  no pg_hba.conf entry for host \"10.0.0.89\", user \"pemadmin\", database \"pem\", SSL on\nFATAL:  no pg_hba.conf entry for host \"10.0.0.89\", user \"pemadmin\", database \"pem\", SSL off\n\nWed Nov 18 16:07:53 2020 ERROR: Unable to connect to Postgres Enterprise Manager Server", "stderr_lines": ["Wed Nov 18 16:07:53 2020 WARNING: ConnectToPEM: unable to connect to PEM database: FATAL:  no pg_hba.conf entry for host \"10.0.0.89\", user \"pemadmin\", database \"pem\", SSL on", "FATAL:  no pg_hba.conf entry for host \"10.0.0.89\", user \"pemadmin\", database \"pem\", SSL off", "", "Wed Nov 18 16:07:53 2020 ERROR: Unable to connect to Postgres Enterprise Manager Server"], "stdout": "", "stdout_lines": []}

PLAY RECAP ******************************************************************************************************************
localhost                  : ok=311  changed=22   unreachable=0    failed=1    skipped=225  rescued=0    ignored=0

**Comment by vibhorkumar123** [comment]
This was fixed in previous release
