### ISSUE TITLE
Google Cloud - Make the Additional Volumes Variables default to disabled in the EDB CLI

### ISSUE THREAD

**Issue by dougortiz** [EnterpriseDB/postgres-deployment#62]
- Comment the prompts for Additional Volumes
- Leave the options available as Terraform Variables

**Comment by dougortiz** [comment]
Tested successfully:
- CentOS8 - Single Node
- RHEL8 - Multi-Node

**Comment by vibhorkumar123** [comment]
With the new design, this is no more needed
