### ISSUE TITLE
Make Postgres deployment to use the inventory file for ansible

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/postgres-deployment#69]
Make Postgres deployment to use the inventory file for ansible

**Comment by dougortiz** [comment]
Tested with AWS successfully:
- Single Node Cluster
- Multi Node Cluster

**Comment by dougortiz** [comment]
Tested with AWS successfully:

- Single Node Cluster: CentOS8 and RHEL8

**Comment by dougortiz** [comment]
Tested with GCP successfully:
- Single Node Cluster: CentOS8 and RHEL8
- Multi-Node Cluster: CentOS8 and RHEL8

**Comment by dougortiz** [comment]
Tested.

Ready for merge.
