### ISSUE TITLE
Add a support for allowing users deploy only one instance.

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/postgres-deployment#7]
Currently, through deployment scripts, we allow users a Highly available Postgres cluster. However, there are some users who want to deploy only primary or one primary and one standby.

**Comment by dougortiz** [comment]
Added functionality to: AWS, Azure and Google Cloud - Testing - 10/08/2020

**Comment by dougortiz** [comment]
@vibhorkumar123 - Ready for review

**Comment by dougortiz** [comment]
@vibhorkumar123 - CentOS8 Single Instance Installation errors out at:

![image](https://user-images.githubusercontent.com/63114888/95891675-6998cb80-0d53-11eb-83ba-337d7c6f41db.png)

**Comment by vibhorkumar123** [comment]
@dougortiz Can you please share the hosts.yml and playbook using for this? (please exclude your credentials)

**Comment by dougortiz** [comment]
Tested on AWS:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS8, CentOS7, RHEL8
PEM Server: 0, Primary: 1
RHEL7 no longer available

**Comment by dougortiz** [comment]
Tested on Azure:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS7, CentOS8, RHEL7, RHEL8
Single Installation: CentOS7, CentOS8, RHEL7, RHEL8
EPAS 13

**Comment by dougortiz** [comment]
Tested on Google Cloud:
Tested on Azure:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS7, CentOS8, RHEL7, RHEL8
Single Installation
EPAS 12
