### ISSUE TITLE
Incorporate "Reference Architecture" Templates to EDB CLI Go

### ISSUE THREAD

**Issue by dougortiz** [EnterpriseDB/postgres-deployment#72]
Functionality:
- No prompting for pem server count
- No prompting for instance count
- Automatically assign pem server count and instance count based on the selected reference architecture
- Only prompt for a "template" name such as:
- Single Node
- Multi-Node

**Comment by dougortiz** [comment]
Tested successfully - AWS:
- Single Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Multi-Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
 
Regression tested successfully:
- Single Node Cluster EPAS: CentOS8 and RHEL8
- Multi-Node Cluster EPAS: CentOS8 and RHEL8

Tested successfully - Azure:
- Single Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Multi-Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Fails because of bug: EPAS - RHEL8: Single and Multi-Node Cluster

Tested successfully - GCP:
- Single Node Cluster - EPAS: CentOS7, CentOS8, RHEL7 and RHEL8
- Multi-Node Cluster - EPAS: CentOS7, CentOS8, RHEL7 and RHEL8

**Comment by vibhorkumar123** [comment]
GoLang work has been postponed for a while, and we have a new interface using python.
