### ISSUE TITLE
Remove the "Update" command for project configuration in EDB - CLI Go

### ISSUE THREAD

**Issue by dougortiz** [EnterpriseDB/postgres-deployment#74]

**Comment by dougortiz** [comment]
![image](https://user-images.githubusercontent.com/63114888/103929703-ade5fe80-50eb-11eb-8091-cdf9b64fb4c8.png)

**Comment by dougortiz** [comment]
Tested successfully - AWS:
- Single Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Multi-Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
 
Regression tested successfully:
- Single Node Cluster EPAS: CentOS8 and RHEL8
- Multi-Node Cluster EPAS: CentOS8 and RHEL8

Tested successfully - Azure:
- Single Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Multi-Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Fails because of bug: EPAS - RHEL8: Single and Multi-Node Cluster

Tested successfully - GCP:
- Single Node Cluster - EPAS: CentOS7, CentOS8, RHEL7 and RHEL8
- Multi-Node Cluster - EPAS: CentOS7, CentOS8, RHEL7 and RHEL8

**Comment by vibhorkumar123** [comment]
GoLang work has been postponed for a while, and we have a new interface using python.
